### ISSUE TITLE
error while running test.py

### ISSUE THREAD

**Issue by Guttappa1238** [rondinellimorais/facial-expression-recognition#1]
Hi,

While running `test.py` i'm getting this error:
```
raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional
```
Please help me to fix this.

![errr](https://user-images.githubusercontent.com/45628395/160804405-01179579-b9a1-4775-af5e-4d669a949104.png)

Thanks advance

**Comment by rondinellimorais** [comment]
Hi @Guttappa1238, thanks for reporting.

The repo was out of date, I added the `requirements.txt` with the necessary dependencies for `test.py` to work.

I also updated the `README.md` to guide you through the setup.

You may have to clone the repo again.

enjoy
